# Generated by Django 3.2.9 on 2021-11-17 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(verbose_name='Height')),
                ('weight', models.IntegerField(verbose_name='Weight')),
            ],
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('sleepHours', models.IntegerField(blank=True, null=True, verbose_name='Hours of Sleep:')),
                ('wakeUp', models.TimeField()),
                ('quality', models.CharField(choices=[('G', 'Good'), ('F', 'Fair'), ('P', 'Poor')], default='F', max_length=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sleep', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Macro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('currentWeight', models.IntegerField(blank=True, null=True, verbose_name='Weight (lb):')),
                ('calories', models.IntegerField(verbose_name='Calories:')),
                ('protein', models.IntegerField(verbose_name='Protein (g):')),
                ('fat', models.IntegerField(verbose_name='Total fat (g):')),
                ('carbs', models.IntegerField(verbose_name='Total carbohydrates (g):')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='macro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
