# Generated by Django 3.2.9 on 2021-12-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='calories',
            field=models.IntegerField(default=0, verbose_name='Calories:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='carbs',
            field=models.IntegerField(default=0, verbose_name='Total carbohydrates (g):'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='fat',
            field=models.IntegerField(default=0, verbose_name='Total fat (g):'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='protein',
            field=models.IntegerField(default=0, verbose_name='Protein (g):'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='index',
            name='height',
            field=models.IntegerField(verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='index',
            name='weight',
            field=models.IntegerField(verbose_name='Weight (Ib)'),
        ),
    ]
