# Generated by Django 3.2.9 on 2021-12-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='height',
            field=models.IntegerField(verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='index',
            name='weight',
            field=models.IntegerField(verbose_name='Weight (Ib)'),
        ),
    ]
