# Generated by Django 3.2.9 on 2021-11-07 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_auto_20211107_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macro',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Macro', to='Dashboard.user'),
        ),
    ]
