# Generated by Django 3.2.9 on 2021-12-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_auto_20211203_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='calories',
            field=models.IntegerField(default=0, verbose_name='Calories:'),
            preserve_default=False,
        ),
    ]
