# Generated by Django 3.2.9 on 2021-11-15 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_auto_20211115_0535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='store',
            new_name='index',
        ),
    ]
