# Generated by Django 3.2.9 on 2021-12-05 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0002_auto_20211204_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='index',
            name='carbs',
            field=models.IntegerField(verbose_name='Total carbs (g):'),
        ),
    ]
