# Generated by Django 3.2.9 on 2021-11-08 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0004_auto_20211107_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macro',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='macro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('sleepHours', models.IntegerField(blank=True, null=True, verbose_name='Hours of Sleep:')),
                ('wakeUp', models.TimeField()),
                ('quality', models.CharField(choices=[('G', 'Good'), ('F', 'Fair'), ('P', 'Poor')], default='F', max_length=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sleep', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
